### PR TITLE
Add Ant build instructions as per #140

### PR DESCRIPTION
**Pull request by pdmholden**

### CODE REVIEW

**Comment by eyedol** [comment]
@pdmholden  Thanks for the pull request. I made some few inline comments about the pull request. Could you fix them, so I can merge the changes.

**Comment by pdmholden** [comment]
Yes, including the local.properties and project.properties files was a mistake. I have pushed a new commit without those. It should be the latest commit in the pull request.

**Comment by pdmholden** [comment]
See SHA: 94a5629279c4e35760e83cd57b644474d7ef5856. That's the latest commit which includes the changes to BUILDING.txt without the erroneously included changes in local.properties and project.properties. I did push -f when I noticed my mistake, which I realize creates confusion.

**Comment by eyedol** [comment]
@pdmholden :+1:

**Pull request merged**
