### PR TITLE
Open GeoSMS

### PR DESCRIPTION
**Pull request by inoran**
Hi Henry, 

I am Chris, slayer's colleague in ITRI Taiwan.
As early mail metioned, we has added functionality to the app that allows user to send incident report using Open GeoSMS standard. And the branch now is up to date with the master branch.

In addition to adding Open GeoSMS functionality, I made some minor change as follows.
1. chinese translation for Taiwan-- creating string.xml of values-zh-rTW in res folder.
2. The user does not need to type phonenumber every time by setting phonenumber in "Setting".
3. fix minor issue about "DIALOG_MULTIPLE_CATEGORY" in  "onPrepareDialog". If a user choose category before clicking "add photo", after added photo, if a user click choose category again, the checked items are not the same as a user choosed before.

### CODE REVIEW

**Comment by eyedol** [comment]
Hi Inoran,

Thanks for the great work you did on opengeosms. Looks great.

I have a question. When submitting a report, what is the use of the transmission field? I see that is accepts only digits? Is that the phone number to send the SMS( the report) to? Also, what's the relation of the phone number field in the settings screen to this? 

Please clarify. Thanks

**Comment by inoran** [comment]
Hi Henry,

Thanks for merging the code :)

You are right, the transmission field is used to type phone number to send Open GeoSMS, and the user can pre-set it in the phone number field of the settings screen.
The reason what I did that is because the phone number now is not the deployment data yet. If the phone number can be one of the deployment data maybe we can remove both of the two fields.
Do you have any idea about it? Does each development will has its own phone number?

I'll let you know if the Open GeoSMS plugin for Ushahidi is being developed.

BR,
Chris

-----Original Message-----

**Comment by eyedol** [comment]
Hi Chris,

Thanks for the clarification. In that case. I'll make the Transmission field only appear in the report submission screen when the phone number isn't set in the Settings screen. Also, I'm going to change the label from 'Transmission' to 'Deployment phone number'. The label, 'Transmission' is a bit confusing.

The deployment phone number can't be retrieved via the API. 

Like I said in the previous email, I have disabled the Open GeoSMS from showing up as a feature in the app until Open GeoSMS plugin for Ushahidi is ready.

Cheers,
Henry!

**Comment by inoran** [comment]
Hi Henry,

It's ok with me to change to label name.

I think if the deployment phone number can be retrieved automatically when the user choose the deployment that would be more convenient. Otherwise, the user need to know the deployment phone number and set it manually.

BR,
Chris

-----Original Message-----

**Comment by inoran** [comment]
Hi Henry,

Could you help me to change the text in the <string name ="app_name"></string> from "Ushahidi_OpenGeoSMSer" to "Ushahidi" in strings.xml(values-zh-rTW)?
I forgot to change the text before merging, sorry.
And what do you think about the operation of deployment phone number as mentioned in last mail?

BR,
Chris

-----Original Message-----
From: 葉采芳 
Sent: Monday, January 09, 2012 5:14 PM
To: Henry Addo
Cc: 莊國煜
Subject: RE: [Ushahidi_Android] Open GeoSMS (#24)

Hi Henry,

It's ok with me to change to label name.

I think if the deployment phone number can be retrieved automatically when the user choose the deployment that would be more convenient. Otherwise, the user need to know the deployment phone number and set it manually.

BR,
Chris

-----Original Message-----

**Comment by eyedol** [comment]
Hi Chris,

In this file https://github.com/inoran/Ushahidi_Android/blob/master/Core/res/values/strings.xml change this line of the code from 

``` xml
<string name="app_name">Ushahidi_OpenGeoSMS</string> 

```

to 

``` xml
<string name="app_name">Ushahidi</string>

```

That is a great idea to get the phone number via the API. That will require working it into the API. I'll see if I can find time to work that into the API. 

Hope that fixes it

**Comment by inoran** [comment]
Hi Henry,

I have changed it.
It's great to hear about that, thanks in advance.

BR,
Chris

-----Original Message-----

**Pull request merged**
