### PR TITLE
report incident using Open GeoSMS

### PR DESCRIPTION
**Pull request by ghost**
# Overview of Changes
## UI:
- when sending report, an alert dialog will pop up asking the user to choose a send method (Internet/Open GeoSMS)
  - save normally when "Internet" is selected
  - ask for phone number when Open GeoSMS is selected
    - send incident report as Open GeoSMS
    - if there are photos associated with the report, it will be saved as a pending Open GeoSMS report to allow uploading photos later
- Added another section for Open GeoSMS reports in `ListReportFragment`
## Database:
- use `incidents.pending=2` to indicate Open GeoSMS reports with pending photo uploads
- added `pendingType` parameter to methods related to pending reports

### CODE REVIEW

**Comment by eyedol** [comment]
@mrl-gt Thanks for the comprehensive addition. I'm really happy to merge this. I have few questions and a suggestion to ask. When does the GeoSMS get triggered? I know an alert dialog shows up when submitting the report. Does this alert dialog shows up by default? If yes, I would suggest a feature, could you make the GeoSMS feature to be enabled via the app setting screen. I'm asking this because not everyone will have GeoSMS enabled on their Ushahidi deployment. Making this behave by default can be an annoying issue if the Ushahidi deployment configured on the app doesn't have GeoSMS enabled.

**Comment by ghost** [comment]
@eyedol Currently the alert dialog show up on default.  I plan to implement a "discover" functionality to detect if an Open GeoSMS plugin is active.  A simple implementation could be to perform a HTTP GET on a specific URL such as http://my.deployment/opengeosms/discover.  If a valid response is returned the deployment is assumed to have Open GeoSMS plugin enabled.  In addition, that URL could return a list of phone numbers so no user input is required,
but I'm not sure if this is a good idea from a security standpoint?

My original plan is to upstream each functionality individually (send, upload photo, discover, improvements/fixes...),
so I can make changes early and incrementally.  If you prefer, I can send a pull request after all functionalities are implemented.  In that case, please take look at the diffs and let me know if there's something I can/should change at this point.

**Comment by eyedol** [comment]
You might want to use this API [http://yourdeployment/api?task=version](http://demo.ushahidi.com/api?task=version) call instead. This API call returns all enabled plugins plus the phone numbers attached to the deployment.

I would say finish with the full feature, send a pull request then I'll merge it for a release. Also, try to keep your fork updated with mine, that way you'll have my latest changes and when merging, it will be much easier. I'm happy to do a code review if you prompt me. If anything let me know.

**Comment by ghost** [comment]
Thanks for the tip on the API.  I will use it to implement "discover".  I have a question about the code review.  How do I "prompt" you?  Do I send you an email with a link to a snapshot of my repo to be reviewed?  Or maybe create another pull request?  Please let me know.  Thanks.

**Comment by eyedol** [comment]
@mrl-gt  Just point me to a commit. Say via email or a comment here on github.

**Comment by eyedol** [comment]
@mrl-gt since this no more needed, mind pulling it out? Thanks.

**Comment by ghost** [comment]
@eyedol Could you tell me how to pull out a pull request?  I can't seem to find a button to do this in the webpage.  Thanks.

**Comment by eyedol** [comment]
I think github canceled it.

**Pull request closed without merging**
