### PR TITLE
Add GeoAvalanche client with integration of custom forms and OpenWeatherMap

### PR DESCRIPTION
**Pull request by francbartoli**
[GeoAvalanche app](https://play.google.com/store/apps/details?id=com.geoavalanche.android.app&hl=it) use cases with reports from custom forms API and map layers from OpenWeatherMap

### CODE REVIEW

**Comment by eyedol** [comment]
@francbartoli Thanks for the `PR` This is a huge one :). Hopefully you haven't added specific changes from your white-labeled instance. Also, could you be more specific with 'GeoAvalanche app' use cases. I have no idea what `GeoAvalanche` is
I'm traveling at the moment but will review this when I'm more settled.

**Comment by francbartoli** [comment]
Hi @eyedol, hopefully not too much invasive :). You can find more information regarding GeoAvalanche by taking a look at [my presentation](http://geobeyond.github.io/presentation-ushahidi-milan2015/#/) at Milan meetup while this PR is tightly coupled with **Ushahidi_Java** [#32](https://github.com/ushahidi/Ushahidi_Java/pull/32) too

cc'ed @aoduor

**Comment by aoduor** [comment]
@francbartoli You, are AWESOME!! Thank you :).

**Comment by aoduor** [comment]
@eyedol, have a look at http://geoavalanche.org/incident/ as well cc @francbartoli

**Comment by francbartoli** [comment]
Thanks @aoduor to put the link directly

**Comment by eyedol** [comment]
@francbartoli Apologies for acting on this late. Just got back from being off.

This `PR` has added a lot of custom implementation related to `GeoAvalanche` this makes it impossible to merge it. Would be great if you could move the custom implementation to a white-label implementation. Liked the custom form implementation and wished we could get that isolated for a merge.

Again, thanks for the `PR`

**Comment by eyedol** [comment]
@francbartoli I will have to close this `PR` as it breaks a lot of the core functionality. It has replaced a lot of the core assets with custom ones. I'm happy to merge changes that enhances or fixes issues with core. I saw that you guys added custom form support, would be great if we could get that in without all the `GeoAvalanche` changes.

**Pull request closed without merging**
